# Generated by Django 5.2.3 on 2025-06-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(
                    max_length=8,
                    error_messages={
                        'max_length': 'el texto debe tener 8 caracteres'},
                    primary_key=True,
                    serialize=False
                )),

                ('ape_nombre', models.CharField(max_length=80)),
                ('fec_registro', models.DateField()),
                ('fec_sistema', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
