# Generated by Django 5.2.3 on 2025-07-04 05:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['ape_nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nom_prod'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ape_nombre',
            field=models.CharField(max_length=80, verbose_name='Apellidos y Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fec_registro',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fec_sistema',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(error_messages={'max_length': 'el texto debe tener 8 caracteres'}, max_length=8, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='des_prod',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fec_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fec_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nom_prod',
            field=models.CharField(max_length=50, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio Unitario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado?')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='venta.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('cod_venta_detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Detalle')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalles', to='venta.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['cod_venta_detalle'],
            },
        ),
        migrations.CreateModel(
            name='VentaSimple',
            fields=[
                ('cod_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de Venta')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado?')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_simples', to='venta.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_simples', to='venta.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta Simple',
                'verbose_name_plural': 'Ventas Simples',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
